package message;
//接口中定义一些常量
//不同的常量值表示不同消息类型

public interface MessageType {

    int PORT = 8080;                     //端口号
    String MESSAGE_LOGIN_SUCCEED = "1";  //登录成功
    String MESSAGE_LOGIN_FAIL = "2";     //登录失败
    String MESSAGE_STUDENT_LOGIN = "3";  //学生登录
    String MESSAGE_TEACHER_LOGIN = "4";  //教师登录
    String MESSAGE_ADMIN_LOGIN = "5";    //管理员登录

    String MESSAGE_STUDENT_REGISTER = "10";             //学生注册
    String MESSAGE_STUDENT_REGISTER_SUCCEED = "11";     //学生注册成功
    String MESSAGE_STUDENT_REGISTER_FAILED = "12";     //学生注册失败
    String MESSAGE_TEACHER_REGISTER = "13";             //老师注册
    String MESSAGE_TEACHER_REGISTER_SUCCEED = "14";     //老师注册成功
    String MESSAGE_TEACHER_REGISTER_FAILED = "15";     //老师注册失败

    String TO_FIND_CERTAIN="16";
    String HAVE_FIND_CERTAIN="17";                     //找到要修改密码的用户
    String NOT_FIND_CERTAIN="18";                      //没有找到要修改密码的用户
    String RESET_PASSWORD="19";                        //开始重置密码
    String RESET_PASSWORD_FAILED = "20";               //重置密码失败
    String RESET_PASSWORD_SUCCEED = "9";              //重置密码成功

    String MESSAGE_CLIENT_EXIT = "0";     //客户端退出

    String MESSAGE_LIBRARY_ENTER="21";   //提取用户id和借阅书籍
    String MESSAGE_LIBRARY_ENTER_RET="21.1";
    String MESSAGE_LIBRARY_ADMIN_ENTER="22"; //提取管理员信息
    String MESSAGE_LIBRARY_ADMIN_ENTER_RET="22.1";
    String MESSAGE_LIBRARY_ADMIN_HANDLE="23";
    String MESSAGE_LIBRARY_ADMIN_ADD="23.1";
    String MESSAGE_LIBRARY_ADMIN_DELETE="23.2";
    String MESSAGE_LIBRARY_TICKET_BACK="24";

    String MESSAGE_LIBRARY_ADMIN_RECEIVE="25";
    String MESSAGE_LIBRARY_BORROW="26";
    String MESSAGE_LIBRARY_BORROW_SUCCEED="26.1";
    String MESSAGE_LIBRARY_BORROW_FAIL_TOO_MANY="26.2";
    String MESSAGE_LIBRARY_BORROW_FAIL_RETURN_FIRST="26.3";
    String MESSAGE_LIBRARY_EXTEND="26.4";
    String MESSAGE_LIBRARY_EXTEND_SUCCEED="26.5";
    String MESSAGE_LIBRARY_EXTEND_FAIL="26.6";
    String MESSAGE_LIBRARY_RET="27";
    String MESSAGE_LIBRARY_RET_SUCCEED="27.1" ;
    String MESSAGE_LIBRARY_QUERY="28";
    String MESSAGE_LIBRARY_APPLICATION="29";
    String MESSAGE_LIBRARY_PAY="30";
    String MESSAGE_LIBRARY_PAY_SUCCEED="30.1";
    String MESSAGE_LIBRARY_PAY_FAIL="30.2";



    String MESSAGE_CURRICULUM_LIST_ALL="31";
    String MESSAGE_CURRICULUM_LIST_ALL_RET="31.1";
    String MESSAGE_CURRICULUM_LIST_MINE="31.5";
    String MESSAGE_CURRICULUM_LIST_MINE_RET="31.6";
    String MESSAGE_CURRICULUM_CHOOSE="32";
    String MESSAGE_CURRICULUM_CHOOSE_SUCCEED="32.1";
    String MESSAGE_CURRICULUM_CHOOSE_CONFLICT="32.2";
    String MESSAGE_CURRICULUM_CHOOSE_FULL="32.3";
    String MESSAGE_CURRICULUM_APPLY="33";
    String MESSAGE_CURRICULUM_APPLY_SUCCEED="33.1";
    String MESSAGE_CURRICULUM_APPLY_FAIL="33.2";
    String MESSAGE_CURRICULUM_LIST_APPLICATION="33.3";
    String MESSAGE_CURRICULUM_LIST_APPLICATION_RET="33.4";
    String MESSAGE_CURRICULUM_APPLICATION_APPROVE="33.5";  //同意加课，Message包getter里写课程id，data里写Course类课程
    String MESSAGE_CURRICULUM_APPLICATION_REFUSE="33.6";  //拒绝加课，Message包getter里写课程id，data里写原因
    String RETURN_STUDENT_INFO="100";           //得到学籍信息
    String RETURN_STUDENT_INFO_SUCCEED="101";   //得到学籍信息成功
    String RETURN_STUDENT_INFO_FAILED="102";    //得到学籍信息失败
    String MESSAGE_CURRICULUM_SHOW_STU="34";
    String MESSAGE_CURRICULUM_SHOW_STU_RET="34.1";
    String MESSAGE_CURRICULUM_SHOW_SCHEDULE="35";
    String MESSAGE_CURRICULUM_SHOW_SCHEDULE_RET="35.1";
    String MESSAGE_CURRICULUM_DELETE="36";
    String MESSAGE_CURRICULUM_LIST_ADMIN_APPLICATION="33.7";
    String MESSAGE_CURRICULUM_LIST_ADMIN_APPLICATION_RET="33.8";
    String MESSAGE_CURRICULUM_QUERY="37";
    String MESSAGE_CURRICULUM_QUERY_RET="37.1";
}
