package message;

//接口中定义一些常量
//不同的常量值表示不同消息类型

public interface MessageType {
    String MESSAGE_LOGIN_SUCCEED = "1";  //登录成功
    String MESSAGE_LOGIN_FAIL = "2";     //登录失败
    String MESSAGE_STUDENT_LOGIN = "3";  //学生登录
    String MESSAGE_TEACHER_LOGIN = "4";  //教师登录
    String MESSAGE_ADMIN_LOGIN = "5";    //管理员登录

    String MESSAGE_LIBRARY_ENTER="21";
    String MESSAGE_LIBRARY_ADMIN_ENTER="22";
    String MESSAGE_LIBRARY_ADMIN_HANDLE="23";
    String MESSAGE_LIBRARY_ADMIN_ADD="23.1";
    String MESSAGE_LIBRARY_ADMIN_DELETE="23.2";
    String MESSAGE_LIBRARY_TICKET_BACK="24";

    String MESSAGE_LIBRARY_ADMIN_RECEIVE="25";
    String MESSAGE_LIBRARY_BORROW="26";
    String MESSAGE_LIBRARY_BORROW_SUCCEED="26.1";
    String MESSAGE_LIBRARY_BORROW_FAIL_TOO_MANY="26.2";
    String MESSAGE_LIBRARY_BORROW_FAIL_RETURN_FIRST="26.3";
    String MESSAGE_LIBRARY_RET="27";
    String MESSAGE_LIBRARY_RET_SUCCEED="27.1" ;
    String MESSAGE_LIBRARY_QUERY="28";
    String MESSAGE_LIBRARY_APPLICATION="29";
    String MESSAGE_LIBRARY_PAY="30";
    String MESSAGE_LIBRARY_PAY_SUCCEED="30.1";
    String MESSAGE_LIBRARY_PAY_FAIL="30.2";

    String MESSAGE_CURRICULUM_LIST="31";
    String MESSAGE_CURRICULUM_CHOOSE="32";
    String MESSAGE_CURRICULUM_CHOOSE_SUCCEED="32.1";
    String MESSAGE_CURRICULUM_CHOOSE_CONFLICT="32.2";
    String MESSAGE_CURRICULUM_CHOOSE_FULL="32.3";
}

